import { Roboto } from "next/font/google";
import './global.scss'
import { AppProvider } from "./provider";
import { Header } from "@/widgets/header";
import { Metadata } from "next";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin", "cyrillic"],
})

export function generateMetadata(): Metadata {
  return {
    title: "Next Shop",
    description: "Generated by create next app",
    authors: [{ name: "Yurii", url: "https://github.com/biyrololo" }],
    icons: "/next-logo.png",
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${roboto.className} antialiased`}
      >
        <AppProvider>
          <Header />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
